### ISSUE TITLE
Versus!

### ISSUE THREAD

**Issue by Francisc** [caitp/gulp-acorn-ddescribe-iit#1]
Hello,

The acorn variation of this much needed Gulp task is the "correct" one since it doesn't throw false positives, right?
[Note: I'm comparing it to `gulp-ddescribe-iit`.]

**Comment by caitp** [comment]
yes. caveat is that it contains more dependencies, and the false positives it corrects may be unlikely

**Comment by Francisc** [comment]
Aha, so you kept both active because you don't trust the deps introduced by acorn enough.
OK, thank you.
